name = "flashgnash-atm9"
author = "flashgnash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ff77ae8cef2ebdf449e45d5413529385122efd8d619f43cbec32b7ead37a631"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
