name = "flashgnash-atm9"
author = "flashgnash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61218ab5a28e513a4eec2c29f66dc37bce6d36b1b5acf53ea52a1260c5e1e4f4"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
